### ISSUE TITLE
Update Game version: 1.0.2 [Global]

### ISSUE THREAD

**Issue by r3x123** [Z4ee/Pipsi-WW-Releases#1]
D:\games\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\Client-Win64-Shipping.exe
Checksum of your game: ED025DFF
Your game version is not supported.

**Comment by KhanhNguyen9872** [comment]
> D:\games\Wuthering Waves\Wuthering Waves Game\Client\Binaries\Win64\Client-Win64-Shipping.exe Checksum of your game: ED025DFF Your game version is not supported.

use old version 1.0.0 wait for update

**Comment by Gaikwad-Prashik-05** [comment]
how do we downgrade ?

**Comment by Opped4** [comment]
how do I download the old version?

**Comment by KhanhNguyen9872** [comment]
> how do I download the old version?

Ask someone who has version 1.0.0 to zip it and send it to you

**Comment by KhanhNguyen9872** [comment]
> share me an old version pws :3

my network very slow, i can't send it to you now, you can try ask another one

**Comment by r3x123** [comment]
> > share me an old version pws :3
> 
> my network very slow, i can't send it to you now, you can try ask another one

i dont believe it reach 70 mb, nice excuse xD

**Comment by kankan1122** [comment]
press ins not working

**Comment by fredovitche** [comment]
i have 1.0.2, and the only thing working is character speed.
