### ISSUE TITLE
Successfully injected but pressing INSERT does nothing

### ISSUE THREAD

**Issue by TehChozinOne** [Z4ee/Pipsi-WW-Releases#11]
Using 0.1.1 with Global game version

**Comment by Darky0307** [comment]
same

**Comment by Xarth-Mai** [comment]
same

**Comment by astonishia** [comment]
Try to disable any overlay e.g. MSi Afterburner, Nvidia shadowplay, or Discord. Mine works fine till today.

**Comment by PROCHITRANK** [comment]
use onscreen keyboard then click insert //laptop keys  issue

**Comment by TehChozinOne** [comment]
> Try to disable any overlay e.g. MSi Afterburner, Nvidia shadowplay, or Discord. Mine works fine till today.

Works after disabling MSI Afterburner. Thanks!
