### ISSUE TITLE
0.1.1 Dump Enemies no longer works on Game Version 1.0.2

### ISSUE THREAD

**Issue by kuro8686** [Z4ee/Pipsi-WW-Releases#3]
Dump Enemies option no longer works and I think hit multiplier doesn't work either.

**Comment by kuro8686** [comment]
If I use the cheat.dll and launcher of 0.1.0, it works again. I'm using Global client btw.

**Comment by andreleon2690** [comment]
> If I use the cheat.dll and launcher of 0.1.0, it works again. I'm using Global client btw.

how you can use 0.1.0 Launcher on new version? it ask to update

**Comment by kuro8686** [comment]
The problem was I always used Pipsi Launcher.exe to start the game and never let the game's launcher update properly to 1.0.2. Everything works now with 0.1.1
