### ISSUE TITLE
reset config

### ISSUE THREAD

**Issue by Vannzee** [Z4ee/Pipsi-WW-Releases#5]
I turned on game speed and it killed the process, now whenever I try to run it it's always fatal error and I cannot open the GUI, how do I reset the config?

**Comment by saefulbarkah** [comment]
delete Pipsi-WW.ini

**Comment by Vannzee** [comment]
> delete Pipsi-WW.ini

thanks for replying, I have found the Pipsi-WW.cfg file, located in the Win64, same as the game .exe
